# Generated by Django 3.0.8 on 2020-08-04 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('LastUpdateTime', models.DateTimeField(auto_now=True, verbose_name='最近修改时间')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='描述')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('dataType', models.CharField(choices=[('formdata', 'formdata'), ('raw', 'raw')], max_length=50, verbose_name='数据类型')),
                ('http', models.CharField(choices=[('http', 'http'), ('https', 'https')], max_length=50, verbose_name='协议名称')),
                ('method', models.CharField(choices=[('POST', 'POST'), ('GET', 'GET'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], max_length=10, verbose_name='请求方法')),
                ('url', models.CharField(max_length=100, verbose_name='接口地址')),
                ('headers', models.TextField(blank=True, null=True, verbose_name='请求头')),
                ('params', models.TextField(blank=True, null=True, verbose_name='表单数据')),
                ('body', models.TextField(blank=True, null=True, verbose_name='源数据')),
            ],
            options={
                'verbose_name': 'TESTCASE',
                'verbose_name_plural': 'TESTCASE管理',
                'db_table': 'gy_tms_api',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('LastUpdateTime', models.DateTimeField(auto_now=True, verbose_name='最近修改时间')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='描述')),
                ('name', models.CharField(max_length=50, verbose_name='项目名称')),
                ('version', models.CharField(max_length=50, verbose_name='版本')),
                ('type', models.CharField(choices=[('Web', 'Web'), ('App', 'App')], max_length=50, verbose_name='类型')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'db_table': 'gy_pms_project',
            },
        ),
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('LastUpdateTime', models.DateTimeField(auto_now=True, verbose_name='最近修改时间')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='描述')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_suite', to='api_test.Project', verbose_name='项目')),
            ],
            options={
                'verbose_name': 'TESTSUITE',
                'verbose_name_plural': 'TESTSUITE管理',
                'db_table': 'gy_tms_suite',
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('LastUpdateTime', models.DateTimeField(auto_now=True, verbose_name='最近修改时间')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='描述')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suite_case', to='api_test.TestSuite', verbose_name='测试用例')),
            ],
            options={
                'verbose_name': 'TESTCASE',
                'verbose_name_plural': 'TESTCASE管理',
                'db_table': 'gy_tms_case',
            },
        ),
        migrations.CreateModel(
            name='GlobalHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('LastUpdateTime', models.DateTimeField(auto_now=True, verbose_name='最近修改时间')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='描述')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('host', models.CharField(max_length=1024, verbose_name='Host地址')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_host', to='api_test.Project', verbose_name='项目')),
            ],
            options={
                'verbose_name': 'HOST',
                'verbose_name_plural': 'HOST管理',
                'db_table': 'gy_pms_host',
            },
        ),
        migrations.CreateModel(
            name='APIResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('LastUpdateTime', models.DateTimeField(auto_now=True, verbose_name='最近修改时间')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='描述')),
                ('request_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='请求方法')),
                ('request_url', models.TextField(blank=True, null=True, verbose_name='请求地址')),
                ('request_headers', models.TextField(blank=True, null=True, verbose_name='请求头')),
                ('request_body', models.TextField(blank=True, null=True, verbose_name='请求正文')),
                ('status_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='响应状态码')),
                ('response_headers', models.TextField(blank=True, null=True, verbose_name='响应头')),
                ('response_body', models.TextField(blank=True, null=True, verbose_name='响应正文')),
                ('assert_result', models.BooleanField(blank=True, null=True, verbose_name='断言结果')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_result', to='api_test.API', verbose_name='执行结果')),
            ],
            options={
                'db_table': 'gy_tms_result',
            },
        ),
        migrations.CreateModel(
            name='APIAssert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('LastUpdateTime', models.DateTimeField(auto_now=True, verbose_name='最近修改时间')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='描述')),
                ('type', models.CharField(choices=[('json', 'json'), ('status_code', 'status_code'), ('reg', 'reg'), ('contains', 'contains')], max_length=50, verbose_name='断言方式')),
                ('pattern', models.CharField(blank=True, max_length=50, null=True, verbose_name='正则或者jsonpath表达式')),
                ('expect', models.CharField(max_length=50, verbose_name='预期结果')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_assert', to='api_test.API', verbose_name='接口')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_assert', to='api_test.TestCase', verbose_name='用例')),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suite_assert', to='api_test.TestSuite', verbose_name='用例集')),
            ],
            options={
                'db_table': 'gy_tms_assert',
            },
        ),
        migrations.AddField(
            model_name='api',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_api', to='api_test.TestCase', verbose_name='用例'),
        ),
        migrations.CreateModel(
            name='APIRelate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('LastUpdateTime', models.DateTimeField(auto_now=True, verbose_name='最近修改时间')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='描述')),
                ('name', models.CharField(max_length=50, verbose_name='变量名')),
                ('type', models.CharField(choices=[('json', 'json'), ('reg', 'reg')], max_length=50, verbose_name='提取方式')),
                ('pattern', models.CharField(max_length=50, verbose_name='正则或者jsonpath表达式')),
                ('value', models.TextField(blank=True, null=True, verbose_name='提取的值')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_relate', to='api_test.API', verbose_name='接口')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_relate', to='api_test.TestCase', verbose_name='用例')),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suite_relate', to='api_test.TestSuite', verbose_name='用例集')),
            ],
            options={
                'db_table': 'gy_tms_relate',
                'unique_together': {('case_id', 'name')},
            },
        ),
    ]
