# Generated by Django 3.0.8 on 2020-07-30 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='apirelate',
            unique_together={('case_id', 'name')},
        ),
    ]
